### ISSUE TITLE
user.get_running_app() sometimes returns a string instead of a ui.App

### ISSUE THREAD

**Issue by rntz** [knausj85/knausj_talon#347]
Try running: `user.switcher_focus("firefox")` while firefox is running
Expected behavior: focuses firefox
Actual behavior: 
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "talon/scripting/actions.py", line 63, in __call__
  File "talon/scripting/types.py", line 360, in call
  File "/home/rntz/.talon/user/knausj/code/switcher.py", line 128, in switcher_focus
    app.focus()
AttributeError: 'str' object has no attribute 'focus'
```

I think the reason for this is that `app` is the string "Firefox" because `user.get_running_app("firefox")` is returning "Firefox" instead of the firefox ui.App instance. This bug may be related to the changes to switcher.py introduced by https://github.com/knausj85/knausj_talon/commit/bd5743b01e14772d61e00465f2b53aa8f90c7cd1.

**Comment by lunixbochs** [comment]
the control flow of get_running_app should probably be inverted like this:
```
if name not in running_application_dict:
    if len(name) < 3:
        raise RuntimeError(
            f'Skipped getting app: "{name}" has less than 3 chars.'
        )
    for running_name, app in ctx.lists["self.running"].items():
        if running_name == name or running_name.lower().startswith(
            name.lower()
        ):
            name = app
            break
for app in ui.apps():
    if app.name == name and not app.background:
        return app
raise RuntimeError(f'App not running: "{name}"')```
